#!/usr/bin/env sh


##
## add to sudoers: 
## echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee /private/etc/sudoers.d/yabai
set -x
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist
sudo yabai --load-sa

#load sa on dock restart
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#close space if window closed and empty
yabai -m signal --add event=window_destroyed action='sh -c "yabai -m query --spaces | jq -r \".[] | select(.windows | length == 0) | .index\" | xargs -I {} yabai -m space {} --destroy"'

yabai -m config external_bar all:0:0 \
    mouse_follows_focus on \
    focus_follows_mouse off \
    window_zoom_persist off \
    window_placement last_child \
    window_shadow on \
    window_opacity on \
    window_opacity_duration 0.1 \
    active_window_opacity 1.0 \
    normal_window_opacity 0.9 \
    window_animation_duration 0.3 \
    window_animation_easing ease_out_expo \
    insert_feedback_color 0xFFFFD699 \
    active_window_border_color 0xFFFFD699 \
    normal_window_border_color 0xFFFFD699 \
    split_ratio 0.50 \
    auto_balance on \
    mouse_modifier fn \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action swap \
    top_padding 2 \
    bottom_padding 2 \
    left_padding 2 \
    right_padding 2 \
    window_gap 3

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Pritunl|LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m config layout bsp
echo "yabai configuration loaded..."
